# Generated by Django 5.1.1 on 2024-10-02 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_pets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_species', models.CharField(max_length=50)),
                ('rarity', models.IntegerField(choices=[(0, 'Common'), (1, 'Uncommon'), (2, 'Rare'), (3, 'Mythical'), (4, 'Legendary')])),
                ('is_busy', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='total_pets',
        ),
        migrations.AddField(
            model_name='inventory',
            name='pet_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.pet'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pets',
        ),
    ]
