# Generated by Django 5.1.1 on 2024-10-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_pet_pet_image_alter_pet_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='rarity',
            field=models.IntegerField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Mythical', 'Mythical'), ('Legendary', 'Legendary')]),
        ),
    ]
