# Generated by Django 5.1.1 on 2024-10-02 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_pet_remove_inventory_total_pets_inventory_pet_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='pet_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.pet'),
        ),
    ]
