# Generated by Django 5.1.1 on 2024-10-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_pet_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='rarity',
            field=models.IntegerField(choices=[(0, 'Common'), (1, 'Uncommon'), (2, 'Rare'), (3, 'Mythical'), (4, 'Legendary')]),
        ),
    ]
