# Generated by Django 5.1.1 on 2024-10-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_pet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='pet_id',
        ),
    ]
