# Generated by Django 4.2.12 on 2024-10-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_pet_pet_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='is_busy',
        ),
        migrations.AddField(
            model_name='inventory',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
    ]
