# Generated by Django 4.2.12 on 2024-10-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_pet_pet_rate_inventory_pet_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
