# Generated by Django 4.2.12 on 2024-10-27 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_pet_pet_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='pet_rate',
        ),
    ]
