# Generated by Django 5.1.1 on 2024-10-27 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_inventory_date_acquired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='date_acquired',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 6, 12, 33, 363838, tzinfo=datetime.timezone.utc)),
        ),
    ]
