# Generated by Django 5.1.1 on 2024-10-27 06:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_inventory_date_acquired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='date_acquired',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
