# Generated by Django 4.2.12 on 2024-10-27 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_alter_pet_rarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('adventure_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_finish', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdventureUser',
            fields=[
                ('adventure_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('adventure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.adventure')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdventurePet',
            fields=[
                ('adventure_pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate_multiplier', models.FloatField()),
                ('rate_on_finish', models.FloatField()),
                ('adventure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.adventure')),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.pet')),
            ],
        ),
    ]
