# Generated by Django 4.2.12 on 2024-10-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
