# Generated by Django 5.1.3 on 2024-11-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='credits_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_changes',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=20),
        ),
    ]
