# Generated by Django 5.1.3 on 2024-11-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_system', '0002_remove_transaction_amount_transaction_credits_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
    ]
