# Generated by Django 5.1.1 on 2024-11-28 03:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0016_alter_inventory_is_busy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('waiting', 'Waiting'), ('success', 'Success')], default='available', max_length=20)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('pet_to_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_to_offer', to='inventory.inventory')),
                ('pet_to_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_to_trade', to='inventory.inventory')),
            ],
        ),
    ]
