# Generated by Django 5.1.1 on 2024-11-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='pet_preferences',
            field=models.JSONField(default=list),
        ),
    ]
