# Generated by Django 5.1.1 on 2024-11-30 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_inventory_is_busy'),
        ('trading', '0002_trade_pet_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='pet_preferences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pet_to_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_to_offer', to='inventory.inventory'),
        ),
    ]
