# Generated by Django 5.1.3 on 2024-12-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_alter_trade_pet_preferences_alter_trade_pet_to_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('waiting', 'Waiting'), ('success', 'Success'), ('closed', 'Closed')], default='available', max_length=20),
        ),
    ]
