# Generated by Django 5.1.3 on 2024-12-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
