# Generated by Django 4.2.12 on 2024-10-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lootbox',
            fields=[
                ('lootbox_id', models.AutoField(primary_key=True, serialize=False)),
                ('lootbox_name', models.CharField(max_length=255)),
                ('rate_cost', models.IntegerField()),
                ('tagged_relevance', models.CharField(max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lootbox_images/')),
            ],
        ),
    ]
