# Generated by Django 4.2.12 on 2024-10-27 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_alter_pet_rarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lootbox',
            fields=[
                ('lootbox_id', models.AutoField(primary_key=True, serialize=False)),
                ('lootbox_name', models.CharField(max_length=255)),
                ('rate_cost', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lootbox_images/')),
                ('tagged_relevance', models.CharField(choices=[('popular', 'Popular'), ('recent', 'Recent'), ('featured', 'Featured')], default='recent', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pull',
            fields=[
                ('pull_id', models.AutoField(primary_key=True, serialize=False)),
                ('roll_info', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('lootbox_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lootbox_market.lootbox')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PullPet',
            fields=[
                ('pull_pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.pet')),
                ('pull_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lootbox_market.pull')),
            ],
        ),
        migrations.CreateModel(
            name='LootboxDropTable',
            fields=[
                ('lootbox_drop_table_id', models.AutoField(primary_key=True, serialize=False)),
                ('lootbox_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lootbox_market.lootbox')),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.pet')),
            ],
        ),
    ]
