# Generated by Django 4.2.12 on 2024-10-16 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lootbox_market', '0003_lootbox_drop_table_lootboxhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lootboxhistory',
            old_name='history_id',
            new_name='lootbox_history_id',
        ),
        migrations.AddField(
            model_name='lootboxhistory',
            name='total_roll',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lootboxhistory',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
