# Generated by Django 4.2.12 on 2024-10-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lootbox_market', '0005_remove_lootbox_drop_table_lootboxdroptable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lootboxdroptable',
            name='drop_rate',
        ),
    ]
