# Generated by Django 5.1.2 on 2024-11-02 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_rewards', '0001_initial'),
        ('inventory', '0010_alter_inventory_is_busy'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='pet_reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.pet'),
        ),
    ]
