# Generated by Django 5.1.2 on 2024-11-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_rewards', '0003_alter_reward_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='credit_reward',
            field=models.IntegerField(default=100),
        ),
    ]
