# Generated by Django 5.1.1 on 2024-10-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_credits',
            field=models.IntegerField(default=500),
        ),
    ]
