# Generated by Django 5.1.2 on 2024-11-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='default_avatar.png', max_length=100),
        ),
    ]
