# Generated by Django 5.1.2 on 2024-11-02 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventory_is_busy'),
        ('login_register', '0006_profile_followers_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='showcased_pets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory'),
        ),
    ]
