# Generated by Django 5.1.2 on 2024-11-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_inventory_is_busy'),
        ('login_register', '0007_profile_showcased_pets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='showcased_pets',
        ),
        migrations.AddField(
            model_name='profile',
            name='showcased_pets',
            field=models.ManyToManyField(blank=True, related_name='showcased_by', to='inventory.inventory'),
        ),
    ]
