# Generated by Django 5.1.2 on 2024-12-01 06:44

import login_register.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0008_remove_profile_showcased_pets_profile_showcased_pets'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uploaded_avatar',
            field=models.ImageField(blank=True, null=True, upload_to=login_register.models.upload_to),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, choices=[('avatar1.png', 'Avatar 1'), ('avatar2.png', 'Avatar 2'), ('avatar3.png', 'Avatar 3'), ('avatar4.png', 'Avatar 4')], max_length=50, null=True),
        ),
    ]
